---
title: "Research Projects"
output: html_document
---

# Population dynamics, coevolution, and assembly of plant-pollinator communities


# Landscape genetics of western columbine (*Aquilegia formosa*) across a forest-meadow mosaic

Woody plant encroachment into alpine meadows may reduce and fragment the habitat available to meadow plant communities. This could reduce population connectivity of alpine plant populations if seeds or pollen fail to disperse across forested areas, reducing effective population sizes, genetic diversity, and adaptive potential.

There are at least two mechanisms by which meadow fragmentation by forest encroachment could reduce the connectivity of meadow plant populations: **1)** a mechanism of isolation-by-resistance in which forest cover impedes pollen and/or seed dispersal to other meadows; **2)**  the possibility that forest cover may reduce resource discovery for pollinators by concealing herbaceous plants, thereby reducing gene flow to plants overgrown by taller forest species. 

Colleagues and I are testing these hypotheses using genetic data from 192 western columbine (*Aquilegia formosa*) plants across a forest-meadow mosaic landscape in the [H. J. Andrews Experimental Forest](https://andrewsforest.oregonstate.edu/). As of December 2021, we have submitted a manuscript describing our findings to *Journal of Ecology* for consideration of publication.

Hypothesis {\textbf{(\textit{i})}} would be supported if neighboring plants in isolated meadows shared greater genetic similarity than neighboring plants in connected meadows, but plants in different isolated meadows showed greater divergence than plants in different but connected meadows. Hypothesis {\textbf{(\textit{ii})}} would be supported if neighboring plants growing underneath taller woody vegetation shared greater genetic similarity than neighboring plants growing in the open, but two plants growing beneath different canopies showed greater divergence than two plants growing equally far apart in space but in the open. 
    
$~$


# Hummingbird movement across a forest-meadow mosaic


# Pollinator recognition in tropical *Heliconia spp.*
