---
layout: single
classes: wide
title:  "A tutorial on analyzing ordinal data"
subtitle: "A GLM approach"
date:   "September 2024"
categories: "Common issues"
usemathjax: true
toc: true
output:
  bookdown::github_document2:
    number_sections: false
    preserve_yaml: true
---

# Introduction

Lately in my consulting practice, I have had many questions about analyzing *ordinal data*, that is, categorical data for which the categories can be ordered in a way that makes sense. For example, the "star system" you may have used to rate that restaurant you visited in Portland that took an hour to seat you, played music too loud to hear the conversation, and then charged absurd prices for mediocre small plates that left you still hungry at the end on some social rating platform is a type of ordinal scale. The star system yields ordinal data because a 3-star rating is greater/better than a two-star rating, but the data aren't really numeric but rather categorical.

Indeed, it may be tempting to treat the data as numeric. After all, an average rating of 3.2 is greater than an average rating of 2.7. However, treating the data as numeric implicitly assumes that 2 is exactly one unit greater than a rating of 1 and one unit less than a rating of 3, and that a 5 is still only one unit better than a 4. But ask yourself, "*is that really the way I rate restaurants?*". Personally, I might give a 4-star rating to any good restaurant, but I reserve a 5-star rating for the best of the best, which are *way* better than the good restaurants. Similarly, 1-star reviews are reserved for the bottom of the barrel and the difference between 1 and 2 stars is a lot greater than the difference between 3 and 4 stars in my mind. 

Because of this *unequal spacing* issue, ordinal data get their own distinction and usually should not be treated as numeric unless well-justified by prior knowledge. But, how can we analyze such data? Below I present one option that is in line with a generalized linear modeling (GLM) approach.

# Motivating example

Assume we have distributed a short survey to two communities, one rural and one urban, and ask the respondents to rate three pictures of the same national park but taken at different locations in terms of how desirable each looks as a vacation destination. The first picture includes strictly "natural" scenery, the second includes some trails through meadows with some people hiking on them, and the last includes a gift shop and a welcome center with a stunning backdrop. The hypothesis is that people will gravitate towards the familiar, so those living in urban areas will rate the second two photos higher than the first since there is more evidence of human influence in them, while people from rural areas will rate the photos with less evidence of human influence higher.

> Important caveat: I am not a social scientist and am just making this stuff up!






