---
layout: single
classes: wide
title:  "A tutorial on analyzing ranking data"
subtitle: "Casting Thurstone Case V models as SEMs"
date:   "July 2024"
categories: "Common issues"
usemathjax: true
toc: true
output:
  bookdown::github_document2:
    number_sections: false
    preserve_yaml: true
---


# Ranking data

Ranking data are common in survey-based research. Ranking data arise from survey questions in which a respondent is asked to rank a set of items by their priority or preference in the view of the respondent. I have recently encountered this type of data in my consulting practice and discovered that there is a relative paucity of approachable material available on analyzing these data, particularly when the research questions involve differences among populations of interest or covariates that could drive different rankings. This post is meant to act as a guide for graduate-level readers and above, with code for fitting the popular Thurstone Case V model with the potential for covariates using R package `lavaan` {% cite lavaan %}. I include some of the mathematical details for interested readers, but I point to recently developed R packages (shamelessly promoting one I am developing as well) that do not require understanding of all the nuts and bolts.

> **Important note**: I am not a social scientist! I do not pretend to know or understand the human psychology and social science underpinning the development of these approaches. To any social scientists out there, please forgive any inaccuracies in that realm.

## The data structure

Ranking data generally come as a set of integers in response to a list of items that a survey respondent is asked to rank in terms of importance, priority, preference, etc. For this post, we will focus on some example data (Table \@ref(tab:eg-data)) in which we assume that 50 respondents were surveyed from 3 populations of interest. To ground this example in the natural resources, assume that the populations of interest are hikers, mountain bikers, and hunters in the central Willamette Valley, OR. Each respondent is asked to rank the items in a list of possible future projects in a local recreation area. The list of items includes *trail maintenance* (of existing trails), *trail construction* (building new trails), *invasive species management*, and *forest thinning*. Assume for the purposes of this post that the respondents answer honestly and that they constitute representative samples of the populations of interest.

```{r echo=FALSE, message=FALSE}
# create some data
# some ranking data from different groups
mus <- list(
  hikers = c(0, 0.5, -0.5, 2),
  mtbikers = c(0, -2, 1, 0.5),
  hunters = c(0, -0.5, -1, -1.5)
)

# create the rank data
ranks <- lapply(
  mus,
  FUN = function(mu){
    sapply(
    1:50,
    function(x){
      s <- rnorm(length(mu), mean = mu)
      return(order(s))
    }
    )
  }
) 

rank_dat <- Reduce(cbind, ranks) |> t() |> as.data.frame()

# add column names and a group label
rank_dat <- dplyr::mutate(
  rank_dat,
  group = rep(names(ranks), each = 50)
)
names(rank_dat)[1:4] <- c("trail_maintenance", "new_trails", "invasives", "thinning")

kableExtra::kable(
  head(rank_dat),
  format = "simple",
  col.names = c("Trail maintenance", "Trail construction", "Invasive species management", "Forest thinning", "Group"),
  caption = "Example dataset. Note that a lower rank means higher priority or preference in this case.",
  label = "eg-data"
)
```

Assume we have the following, seemingly straightforward research question:

**Research question**: Do different user groups prefer different management actions for the upcoming projects?

Addressing this question is trickier than it might seem on first glance. These data are multivariate, since the measured unit is the respondent and a respondent's answer includes a set of four numbers, discrete, and bounded on both ends (i.e., a rank of $$>4$$ or $$<1$$ is not possible). Any one of these characteristics could complicate an analysis on its own; now we get all of them at once!

# Analysis

Before we get into the approach this post is meant to introduce, let's consider some possible alternatives and their potential pitfalls. I only include these considerations because I have seen these approaches used in practice without recognition of the issues.

## Potential work-arounds?

### ANOVA?

In a simpler situation than our example above in which the question is simply *is there a preference for some items over others*, it may be tempting to make an appeal to the central limit theorem (CLT) and argue that, despite the discrete nature of the data, the sampling distribution of the mean rank should approach a normal distribution with large sample sizes ($$n > 30$$?). Thus, perhaps one-way ANOVA may be appropriate, treating each item as a group (*factor level* in the classical ANOVA lingo) and testing the null hypothesis $$H_0: \mu_1 = \mu_2 = \mu_3 = ... = \mu_K$$, where $$K$$ is the number of items and $$\mu_k$$ is the mean rank of the $$k^\text{th}$$ item? However, the first problem with this is that ranks from the same respondent are not independent of one another. If I know that item 1 was ranked first by respondent $$i$$, this gives me information about the possible ranks of the remaining items ranked by respondent $$i$$. This clearly violates the assumption of independent errors. Interestingly, this will actually make the analysis overly conservative rather than anti-conservative as is usually the case when the independence assumption is violated. This is because the errors within a respondent are *negatively* correlated, since, if I know item 1 is ranked with high priority (i.e., ranked with a small number), then the remaining items will be given lower priority (i.e., ranked with a large number). This inverse relationship induced negative correlation among the errors within a respondent.

### LMMs?

Indeed, an overly conservative analysis may not be much of a concern in some cases. For example, if the goal is to inform policy or management decisions, caution may be warranted. Alternatively, one may want confidence intervals that are as tight as they can be and still be valid. In this case, one may argue that we have tools to account for correlated errors and that a linear mixed model with an unstructured correlation matrix (see, for example, `?nlme::corStruct()` {% cite nlme %}) to model the correlation of the errors within a respondent may be a good option. Furthermore, one could concoct a model to address the research question above using factors for the group to which the respondent belongs and the item being ranked, as well as the interaction between the two factors. This very well might be a reasonable approach, *particularly if the sample sizes are large and the mean ranks don't get too close to the bounds of 1 and* $$K$$. Otherwise, due to the bounds on the support of the response variable, residuals plots may commonly look like Figure \@ref(fig:bad-resids), and an appeal to the CLT may not be justified. **However**, there is one additional problem with this approach that is more philosophical than it is technically a statistical issue. Namely, is it really a good idea to say that the difference between a rank of 1 and 2 is the same as the difference between ranks 2 and 3? This is what we are implying by treating the ranks as integer values in the approaches discussed thus far, but I would argue that this seems to me to like it would rarely be a good idea.

As an extreme example, consider the case where I am asked to rank the foods ice cream (`r emoji::emoji("icecream")`), pie (`r emoji::emoji("pie")`), and broccoli (`r emoji::emoji("broccoli")`) in terms of what I want for dessert tonight. If I give these items ranks $$\{1,2,3\}$$, is it reasonable to think that my preference for ice cream over pie is of the same magnitude as my preference for pie over broccoli!? Don't get me wrong, I love broccoli, but for dessert, pie and ice cream are *way* better. The models discussed below handle all of these issues quite elegantly.

## Thurstone's model

Louis Leon Thurstone was an early pioneer in psychology and psychometrics. He helped develop many analytical approaches still commonly used in practice today, including factor analysis. In fact, the Thurstone case V model that this post is about is a special case of confirmatory factor analysis. Thurstone conceptualized his models assuming that a person's view or opinion of an item they are presented with in a survey is on a continuum, a scale that he called the *utility scale*. In other words, the item holds a certain *utility*^[*Utility* seems very, well, utilitarian to me. I would suggest that *value* might be better terminology for this day and age.] to a person that is not on a 1-5 or 1-10 integer scale as we often present in a survey. Similarly, if the same item is presented to a population of people, the utilities for these people should represent a distribution of utilities.


Unfortunately, we have no way to measure the utility an item holds for a person, but we can get a sense of utility distributions relative to one another for a population of interest. We do this by asking a random sample of respondents to rank a set of items in terms of the target of the research (e.g., least to most preferred). The Thurstone models then assume that, if a certain person is presented with items $$1,2,...,K$$, then they will have a realized vector of utilities $${\bf u} = (u_1, u_2, ..., u_K)^\top$$.



## References

{% bibliography --file references_ranking_data_blog.bib %}








